MindPlaceClient/Pages/DashBoard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using MindPlaceClient.Code;
using MindPlaceClient.Dtos;
using MindPlaceClient.MindPlaceApiService;
using Newtonsoft.Json;

namespace MindPlaceClient.Pages
{
    [Authorize]
    public class DashBoardModel : BasePageModel
    {
        public UserResponseDto UserDetails { get; set; }
        public ICollection<QuestionResponseDto> Questions { get; set; } = new List<QuestionResponseDto>();

        //[BindProperty]
        public QuestionDto QuestionDetails { get; set; }

        public DashBoardModel(IConfiguration configuration, IHttpClientFactory clientFactory)
            : base(configuration, clientFactory.CreateClient())
        {
        }

        public async Task<ActionResult> OnGetAsync()
        {
            //get user
            try
            {
                TryAddBearerTokenToHeader();
                //start tasks
                var userTask = _mindPlaceClient.GetUserAsync(User.GetLoggedOnUsername());
                var userQuestionsTask = _mindPlaceClient.GetUserQuestionsAsync(User.GetLoggedOnUsername());
                //wait for all task to complete
                await Task.WhenAll(userTask, userQuestionsTask);

                UserDetails = userTask.Result;
                Questions = await _mindPlaceClient.GetUserQuestionsAsync(User.GetLoggedOnUsername());
                if (UserDetails == null)
                {
                    return NotFound();
                }
            }
            catch (AggregateException ae)
            {
                foreach (var ex in ae.InnerExceptions)
                {
                    ErrorMessage += HandleException(ex);
                }
            }
            catch (Exception ex)
            {
                ErrorMessage += HandleException(ex);
            }

            return Page();
        }

        public async Task<ActionResult> OnPostAskQuestionAsync(QuestionDto questionDetails)
        {
            //get user
            if (ModelState.IsValid)
            {
                try
                {
                    TryAddBearerTokenToHeader();
                    var questionResponse = await _mindPlaceClient.AddQuestionAsync(questionDetails);

                    return new JsonResult(new { Success = true });
                }
                catch (ApiException ex) when (!string.IsNullOrWhiteSpace(ex.Response) && ex.Response.Contains("detail"))
                {
                    //error from unchase libary.
                    //make sure a "problemDetails" was returned before deserialization
                    var response = JsonConvert.DeserializeObject<MindPlaceApiService.ProblemDetails>(ex.Response);
                    //ModelState.AddModelError(string.Empty, response.Detail);
                    return new JsonResult(new { Success = false, Message = response.Detail });
                }
                catch (Exception ex)
                {
                    return new JsonResult(new { Success = false, Message = ex.Message });
                    //ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            //MODEL ERROR
            return new JsonResult(new
            {
                success = false,
                errorType = "Model",
                errorModel = ModelState.Keys.Where(mk => ModelState[mk].Errors.Count > 0).Select(jk => new {
                    key = jk,
                    errors = ModelState[jk].Errors.Select(e => e.ErrorMessage).ToArray()
                })
            });
        }

        public async Task<ActionResult> OnPostEditQuestionAsync(int questionId, QuestionDto questionDetails)
        {
            //get user
            if (ModelState.IsValid)
            {
                try
                {
                    TryAddBearerTokenToHeader();
                    var questionResponse = await _mindPlaceClient.EditQuestionAsync(questionId, questionDetails);

                    return new JsonResult(new { Success = true });
                }
                catch (ApiException ex) when (!string.IsNullOrWhiteSpace(ex.Response) && ex.Response.Contains("detail"))
                {
                    //error from unchase libary.
                    //make sure a "problemDetails" was returned before deserialization
                    var response = JsonConvert.DeserializeObject<MindPlaceApiService.ProblemDetails>(ex.Response);
                    //ModelState.AddModelError(string.Empty, response.Detail);
                    return new JsonResult(new { Success = false, Message = response.Detail });
                }
                catch (Exception ex)
                {
                    return new JsonResult(new { Success = false, Message = ex.Message });
                    //ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            //MODEL ERROR
            return new JsonResult(new
            {
                success = false,
                errorType = "Model",
                errorModel = ModelState.Keys.Where(mk => ModelState[mk].Errors.Count > 0).Select(jk => new {
                    key = jk,
                    errors = ModelState[jk].Errors.Select(e => e.ErrorMessage).ToArray()
                })
            });
        }

        public async Task<ActionResult> OnPostDeleteQuestionAsync([FromForm]int questionId)
        {
            //get user
            if (questionId > 0)
            {
                try
                {
                    TryAddBearerTokenToHeader();
                    var questionResponse = await _mindPlaceClient.DeleteQuestionAsync(questionId);

                    return new JsonResult(new { Success = true });
                }
                catch (ApiException ex) when (!string.IsNullOrWhiteSpace(ex.Response) && ex.Response.Contains("detail"))
                {
                    //error from unchase libary.
                    //make sure a "problemDetails" was returned before deserialization
                    var response = JsonConvert.DeserializeObject<MindPlaceApiService.ProblemDetails>(ex.Response);
                    //ModelState.AddModelError(string.Empty, response.Detail);
                    return new JsonResult(new { Success = false, Message = response.Detail });
                }
                catch (Exception ex)
                {
                    return new JsonResult(new { Success = false, Message = ex.Message });
                    //ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            //MODEL ERROR
            return new JsonResult(new { Success = false, Message = "invalid parameter 'questionid" });
        }

        public async Task<ActionResult> OnGetLoadCommentsAsync(int questionId)
        {
            //get comments
            try
            {
                TryAddBearerTokenToHeader();
                var commentResponse = await _mindPlaceClient.GetCommentsAsync(questionId);

                return new JsonResult(new { Success = true, Data = commentResponse });
            }
            catch (ApiException ex) when (!string.IsNullOrWhiteSpace(ex.Response) && ex.Response.Contains("detail"))
            {
                //error from unchase libary.
                //make sure a "problemDetails" was returned before deserialization
                var response = JsonConvert.DeserializeObject<MindPlaceApiService.ProblemDetails>(ex.Response);
                return new JsonResult(new { Success = false, Message = response.Detail });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { Success = false, Message = ex.Message });
            }

           
        }

        public async Task<ActionResult> OnPostMakeCommentAsync(NewComment comment)
        {
            //get user
            if (ModelState.IsValid)
            {
                try
                {
                    TryAddBearerTokenToHeader();
                    var commentResponse = await _mindPlaceClient.AddCommentAsync(comment.questionId, comment);

                    return new JsonResult(new { Success = true, CurrentUser = User.GetFullName() });
                }
                catch (ApiException ex) when (!string.IsNullOrWhiteSpace(ex.Response) && ex.Response.Contains("detail"))
                {
                    //error from unchase libary.
                    //make sure a "problemDetails" was returned before deserialization
                    var response = JsonConvert.DeserializeObject<MindPlaceApiService.ProblemDetails>(ex.Response);
                    return new JsonResult(new { Success = false, Message = response.Detail });
                }
                catch (Exception ex)
                {
                    return new JsonResult(new { Success = false, Message = ex.Message });
                }
            }

            //MODEL ERROR
            return new JsonResult(new
            {
                success = false,
                errorType = "Model",
                errorModel = ModelState.Keys.Where(mk => ModelState[mk].Errors.Count > 0).Select(jk => new {
                    key = jk,
                    errors = ModelState[jk].Errors.Select(e => e.ErrorMessage).ToArray()
                })
            });;
        }
    }

    
}

MindPlaceClient/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MindPlaceClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string Message { get; set; }
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MindPlaceClient/Pages/Forum.cshtml.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using JW;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using MindPlaceClient.Code;
using MindPlaceClient.MindPlaceApiService;
using Newtonsoft.Json;

namespace MindPlaceClient.Pages
{
    public class ForumModel : BasePageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterText { get; set; } = "";
        [BindProperty(SupportsGet = true)]
        public string SearchText { get; set; } = "";
        public int PageSize { get; private set; } = 10;

        [BindProperty]
        public ForumQuestionDto QuestionDetails { get; set; }

        public Pager Pager { get; set; }
        public List<ForumQuestionResponseDto> Questions { get; set; } = new List<ForumQuestionResponseDto>();

        public ForumModel(IConfiguration configuration, IHttpClientFactory clientFactory)
            : base(configuration, clientFactory.CreateClient())
        {
        }

        public async Task<ActionResult> OnGetAsync(int pageNumber = 1)
        {
            try
            {
                var response = await _mindPlaceClient.GetForumQuestionsAsync(FilterText, SearchText, pageNumber, PageSize);
                Questions = response.Data.ToList();
                // get pagination info for the current page
                Pager = new Pager(response.Meta.TotalCount, pageNumber, PageSize, 5);
            }
            catch (Exception ex)
            {
                //error
                var exceptionMessage = HandleException(ex);
                return RedirectToPage("Error", new { Message = exceptionMessage });
            }
            return Page();
        }

        public async Task<ActionResult> OnGetFetchTagsAsync()
        {
            try
            {
                var tags = await _mindPlaceClient.ListTagsAsync();
                return new JsonResult(new { Success = true, Data = tags });
            }
            catch (Exception ex)
            {
                //error
                var exceptionMessage = HandleException(ex);
                return new JsonResult(new { Success = false, Message = exceptionMessage });
            }
        }

        public async Task<ActionResult> OnPostAsync(ForumQuestionDto questionDetails)
        {
            //if (questionDetails.Tags.Count < 1 || questionDetails.Tags.Contains(null))
            //{
            //    ModelState.TryAddModelError("questionDetails.Tags", "Please enter a valid question tag.");
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    TryAddBearerTokenToHeader();
                    var questionResponse = await _mindPlaceClient.AddForumQuestionAsync(questionDetails);

                    return new JsonResult(new { Success = true, Data = questionResponse });
                }
                catch (Exception ex)
                {
                    var exceptionMessage = HandleException(ex);
                    return new JsonResult(new { Success = false, Message = exceptionMessage });
                }
            }

            //MODEL ERROR
            return new JsonResult(new
            {
                success = false,
                errorType = "Model",
                errorModel = ModelState.Keys.Where(mk => ModelState[mk].Errors.Count > 0).Select(jk => new {
                    key = jk,
                    errors = ModelState[jk].Errors.Select(e => e.ErrorMessage).ToArray()
                })
            });
        }

    }
}

MindPlaceClient/Pages/ForumPost.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using MindPlaceClient.Code;
using MindPlaceClient.MindPlaceApiService;

namespace MindPlaceClient.Pages
{
    public class ForumPostModel : BasePageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterText { get; set; } = "";
        [BindProperty(SupportsGet = true)]
        public string SearchText { get; set; } = "";

        public ForumPostResponseDto Post { get; set; }

        public ForumPostModel(IConfiguration configuration, IHttpClientFactory clientFactory)
           : base(configuration, clientFactory.CreateClient())
        {
        }

        public async Task<ActionResult> OnGetAsync(int postId)
        {
            if (postId <= 0)
            {
                return NotFound();
            }

            try
            {
                TryAddBearerTokenToHeader();
                Post = await _mindPlaceClient.GetForumQuestionAsync(postId);
                
                if (Post == null)
                {
                    //the id doesn't exist in db;
                    return NotFound();
                }

            }
            catch (Exception ex)
            {
                var exceptionMessage = HandleException(ex);
                return NotFound();
            }

            return Page();
        }
    }
}

MindPlaceClient/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MindPlaceClient.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public RedirectToPageResult OnGet()
        {
            return RedirectToPage("/Public/Login");
        }
    }
}

MindPlaceClient/Pages/Messages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MindPlaceClient.Pages
{
    public class MessagesModel : PageModel
    {
        public PageResult OnGet()
        {
            return Page();
        }
    }
}

MindPlaceClient/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MindPlaceClient.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MindPlaceClient/Pages/ForumPost.cshtml
@page "/forum/posts/{postId:int}/{handler?}"
@model MindPlaceClient.Pages.ForumPostModel
@{
    ViewData["Title"] = "Forum";
}


<section class="forum-page">
    <div class="container">
        <div class="forum-questions-sec">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="forum-post-view">
                        <div class="usr-question">
                            <div class="usr_img">
                                <img src="/images/resources/pf-icon1.png" alt="">
                            </div>
                            <div class="usr_quest">
                                <h3>@Model.Post.Title</h3>
                                <span>
                                    <i class="fa fa-clock-o"></i><span class="mb-0" data-date-string='@Model.Post.CreatedOn.ToString("yyyy-MM-ddTHH:mm:ssZ")'></span>
                                </span>
                                <ul class="react-links d-none">
                                    <li><a href="#" title=""><i class="fa fa-heart"></i> Vote 150</a></li>
                                    <li><a href="#" title=""><i class="fa fa-share-alt"></i> Share</a></li>
                                </ul>
                                @*<ul class="quest-tags mt-0">
                                    @if (Model.Post.Tags.Any())
                                    {
                                        foreach (var tag in Model.Post.Tags)
                                        {
                                            <li><a href="#" title="Tag Name">@tag</a></li>
                                        }
                                    }
                                </ul>*@
                                <p>
                                    @Model.Post.Content
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="post-comment-box">
                        <h3 class="mb-0">
                            @if(Model.Post.CommentCount > 0)
                            {
                                @("Comments " + Model.Post.CommentCount)
                            }
                            else
                            {
                                @("Comment 0")
                            }
                        </h3>

                        <div class="comment-section">
                            <div class="comment-sec">
                                <ul>
                                    @if (Model.Post.TopComments.Any())
                                    {
                                        foreach (var comment in Model.Post.TopComments)
                                        {
                                            <li>
                                                <div class="comment-list pb-0">
                                                    <div class="bg-img">
                                                        <img src="/images/resources/pf-icon2.png" alt="">
                                                    </div>
                                                    <div class="comment">
                                                        <h3>@comment.User.FullName</h3>
                                                        <span>
                                                            <img src="/images/clock.png" alt=""> 
                                                            <span data-date-string='@comment.CreatedOn.ToString("yyyy-MM-ddTHH:mm:ssZ")'></span>
                                                        </span>
                                                        <p>@comment.Content</p>
                                                    </div>
                                                </div>
                                            </li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>



                        <div class="user-poster">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="usr-post-img">
                                    <img src="/images/resources/pf-icon3.png" alt="">
                                </div>
                                <div class="post_comment_sec">
                                    <form id="AddComment" method="post" data-post-id="@Model.Post.Id" asp-page="/DashBoard" asp-route-username="@User.GetLoggedOnUsername()" asp-page-handler="MakeComment">
                                        <textarea placeholder="Your Answer" name="content"></textarea>
                                        <button type="submit" disabled>Post Answer</button>
                                    </form>
                                </div>
                            }
                            else
                            {
                                <h5 class="h5 text-black-50">
                                    <a asp-page="/Public/Login" asp-route-ReturnUrl="@HttpContext.Request.Path.Value">Login</a> to leave a comment.
                                </h5>
                            }
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="widget widget-user">
                        <h3 class="title-wd">Top User of the Week</h3>
                        <ul>
                            <li>
                                <div class="usr-msg-details">
                                    <div class="usr-ms-img">
                                        <img src="/images/resources/m-img1.png" alt="">
                                    </div>
                                    <div class="usr-mg-info">
                                        <h3>Jessica William</h3>
                                        <p>Graphic Designer </p>
                                    </div>
                                </div>
                                <span>
                                    <img src="/images/price1.png" alt="">1185
                                </span>
                            </li>
                            <li>
                                <div class="usr-msg-details">
                                    <div class="usr-ms-img">
                                        <img src="/images/resources/m-img2.png" alt="">
                                    </div>
                                    <div class="usr-mg-info">
                                        <h3>John Doe</h3>
                                        <p>PHP Developer</p>
                                    </div>
                                </div>
                                <span>
                                    <img src="/images/price2.png" alt="">1165
                                </span>
                            </li>
                            <li>
                                <div class="usr-msg-details">
                                    <div class="usr-ms-img">
                                        <img src="/images/resources/m-img3.png" alt="">
                                    </div>
                                    <div class="usr-mg-info">
                                        <h3>Poonam</h3>
                                        <p>Wordpress Developer </p>
                                    </div>
                                </div>
                                <span>
                                    <img src="/images/price3.png" alt="">1120
                                </span>
                            </li>
                            <li>
                                <div class="usr-msg-details">
                                    <div class="usr-ms-img">
                                        <img src="/images/resources/m-img4.png" alt="">
                                    </div>
                                    <div class="usr-mg-info">
                                        <h3>Bill Gates</h3>
                                        <p>C & C++ Developer </p>
                                    </div>
                                </div>
                                <span>
                                    <img src="/images/price4.png" alt="">1009
                                </span>
                            </li>
                        </ul>
                    </div>
                    <div class="widget widget-adver">
                        <img src="/images/resources/adver-img.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MindPlaceClient/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

MindPlaceClient/Pages/Professionals.cshtml
@page "{handler?}"
@model MindPlaceClient.Pages.ProfessionalsModel
@{
    ViewData["Title"] = "Therapist";
}

<section class="companies-info">
    <div class="container">
        <div class="company-title">
            <h3>Professionals</h3>
        </div>
        <div class="companies-list">
            <div class="row">

                @if (Model.Professionals.Any())
                {
                    foreach (var professional in Model.Professionals)
                    {
                        //check that the professional isn't following the current use and the current user hasn't subscribed to the professional
                        //if (!professional.Following.Any(u => u.Username == User.GetLoggedOnUsername())
                        //                && !professional.Followers.Any(u => u.Username == User.GetLoggedOnUsername()))
                        //{

                        //}

                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div id="prof_@professional.Username" class="company_profile_info">
                                <div class="company-up-info">
                                    <img src="~/assets/img/user1.png" alt="">
                                    <h3>
                                        @professional.FullName
                                    </h3>

                                    <ul>
                                        <li>
                                            <a href="#" title="subscribe" class="follow">Subscribe</a>
                                        </li>
                                    </ul>
                                </div>
                                <a href="#profileModal" class="view-more-pro" data-toggle="modal">
                                    View Profile
                                </a>
                            </div>
                        </div>

                    }
                }
                else
                {
                    <h3 class="align-middle text-black-50 text-center col-12">No Professional Found.</h3>
                }

                @*Used in javascript*@
                <form method="post" class="d-none"></form>
            </div>
        </div>
        <div class="process-comm d-none">
            <div class="spinner">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
    </div>
</section>